# Generated by Django 5.0.7 on 2024-07-30 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_estudiante_edad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entregable',
            old_name='fecha_de_entrega',
            new_name='fecha_entrega',
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='apellido',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='apellido',
            field=models.CharField(max_length=20),
        ),
    ]
